# Generated by Django 5.0.1 on 2024-08-22 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='departamento',
            new_name='position',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='funcionalidade',
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('FR POSITION_', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], max_length=50, null=True),
        ),
    ]
