# Generated by Django 5.0.1 on 2024-08-22 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_departamento_customuser_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('TI', 'Tecnologia da Informação'), ('ADM', 'Administrativo')], max_length=50, null=True),
        ),
    ]
