# Generated by Django 5.0.1 on 2024-09-28 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kanban', '0001_initial'),
        ('priority', '0001_initial'),
        ('status', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('expected_conclusion', models.DateField(blank=True, null=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('author', models.ManyToManyField(related_name='task_author', to=settings.AUTH_USER_MODEL)),
                ('kanban', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_kanban', to='kanban.kanban')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_status', to='status.status')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_priority', to='priority.priority')),
            ],
        ),
    ]
