# Generated by Django 5.0.1 on 2024-09-26 00:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordcode',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
