# Generated by Django 5.0.1 on 2024-09-28 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('color', models.CharField(max_length=10)),
                ('date_created', models.DateTimeField()),
                ('kanban', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kanban_status', to='kanban.kanban')),
            ],
        ),
    ]
